import subprocess
import time

#==============================================================================#
# Global Variables
#==============================================================================#
# cplex path (change if your cplex is in a different path)
CPLEX = "/home/cosc/student/ysk28/cplex/cplex/bin/x86-64_linux/cplex"
# lp file path (change if your files are in a different file)
FILE = "/home/cosc/student/ysk28/"

#==============================================================================#
# Main function - loops through all the lp file generated by lp_gen.py and pass
# it through to cplex and outputs it into a text file
#==============================================================================#
for i in range (3, 8):
    filename = "out%s.lp" %i
    # cplex command line 
    cmd = CPLEX, "-c", 'read ' + FILE + filename, "optimize", 
    "display solution variables -"
    # calls a subprocess to run cplex
    process = subprocess.Popen(cmd, stdout = open("out%s.txt" %i, "wb"));
    start_time = time.time()
    # wait for process to finish
    process.wait()
    process_time = time.time() - start_time
    print("Process time for %s transit node is: " %i, process_time)
